export const ActionTypes = {
  TOPIC_ADDED: "TOPIC ADDED",
  WIKI_PARAGRAPHS_ADDED: "WIKI PARAGRAPHS ADDED",
  USER_QUERY_ADDED: "USER QUERY ADDED",
  BERT_PASSAGE_ADDED: "BERT PASSAGE ADDED",
  BERT_ANSWERS_ADDED: "BERT ANSWERS ADDED",
  BERT_ANSWERS_STATE: "BERT ANSWER STATE",
  SET_VIEW: "SET VIEW",
  SET_NOTIFICATION: "SET NOTIFICATION",
};
