export const ActionTypes = {
  TOPIC_ADDED: "TOPIC ADDED",
  WIKI_PARAGRAPHS_ADDED: "WIKI PARAGRAPHS ADDED",
  WIKI_URL_ADDED: "WIKI URL ADDED",
  WIKI_SECONDARY_LINKS: "WIKI SECONDARY LINKS ADDED",
  USER_QUERY_ADDED: "USER QUERY ADDED",
  BERT_PASSAGE_ADDED: "BERT PASSAGE ADDED",
  BERT_ANSWERS_ADDED: "BERT ANSWERS ADDED",
  BERT_ANSWERS_STATE: "BERT ANSWER STATE CHANGED",
  SET_VIEW: "VIEW CHANGED",
  SET_NOTIFICATION: "NOTIFICATION ADDED",
};
